const PROFISSOES_DATA = [
  {
    "id": "A001",
    "categoria": "Automotivo",
    "nome": "Insulfilm automotivo",
    "unidade": "carro",
    "producao_dia": 3.5,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Filme insulfilm (3M, Maxterm ou Vkool)",
      "rodo de silicone",
      "lâmina"
    ],
    "tempo_por_unidade_h": 2.3,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Rodo", "Espátula", "Pistola de ar quente"],
    "epi_necessario": ["Luva de proteção", "Óculos de segurança"],
    "tags": ["insulfilm", "automotivo", "carro", "película"],
    "obs": "Média 3–4 carros/dia. SUVs e pickups contam como 1.5 carro pelo tamanho maior.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "A002",
    "categoria": "Automotivo",
    "nome": "Polimento automotivo completo",
    "unidade": "carro",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Politriz",
      "compound",
      "polish",
      "pano de microfibra"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "alto",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Politriz orbital ou rotativa"],
    "epi_necessario": ["Máscara contra pó", "Óculos de segurança", "Protetor auricular"],
    "tags": ["polimento", "automotivo", "carro", "estética"],
    "obs": "Polimento completo com 3 etapas. Polimento simples (1 etapa) permite 3–4 carros/dia.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "A003",
    "categoria": "Automotivo",
    "nome": "Higienização interna automotiva",
    "unidade": "carro",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Aspirador",
      "extratora",
      "produtos de limpeza",
      "escova"
    ],
    "tempo_por_unidade_h": 2.5,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": true,
    "equipamentos": ["Aspirador", "Extratora ou vapor"],
    "epi_necessario": ["Luva de borracha", "Máscara"],
    "tags": ["higienização", "automotivo", "limpeza interna"],
    "obs": "Inclui bancos, tapetes, painel e teto. Carros muito sujos acrescentar 30% no valor.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "A004",
    "categoria": "Automotivo",
    "nome": "Insulfilm residencial (vidros)",
    "unidade": "m2",
    "producao_dia": 10,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Filme residencial",
      "rodo",
      "lâmina"
    ],
    "tempo_por_unidade_h": 0.8,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Rodo", "Lâmina", "Borrifador"],
    "epi_necessario": [],
    "tags": ["insulfilm", "residencial", "vidro", "película"],
    "obs": "Vidros planos. Vidros curvos ou com veneziana reduzem produção em 30%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "P001",
    "categoria": "Pintura",
    "nome": "Pintura interna (tinta látex 2 demãos)",
    "unidade": "m2",
    "producao_dia": 25,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Tinta",
      "rolo",
      "bandeja",
      "fita crepe",
      "lona"
    ],
    "tempo_por_unidade_h": 0.32,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Rolo", "Trincha", "Bandeja"],
    "epi_necessario": ["Máscara", "Óculos de proteção"],
    "tags": ["pintura", "interna", "parede", "tinta"],
    "obs": "Paredes já preparadas (sem massa corrida). Inclui proteção de rodapé e janelas.",
    "requer_visita_tecnica": false,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "P002",
    "categoria": "Pintura",
    "nome": "Pintura interna com massa corrida",
    "unidade": "m2",
    "producao_dia": 15,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Massa corrida PVA",
      "lixa",
      "tinta",
      "rolo"
    ],
    "tempo_por_unidade_h": 0.53,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Espátula", "Desempenadeira de plástico", "Lixadeira manual"],
    "epi_necessario": ["Máscara contra pó", "Óculos de segurança"],
    "tags": ["pintura", "massa corrida", "acabamento"],
    "obs": "Inclui lixamento, 2 demãos de massa e 2 demãos de tinta.",
    "requer_visita_tecnica": false,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "P003",
    "categoria": "Pintura",
    "nome": "Pintura externa (fachada)",
    "unidade": "m2",
    "producao_dia": 18,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Tinta acrílica exterior",
      "escada",
      "rolo de cabo longo"
    ],
    "tempo_por_unidade_h": 0.44,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": false,
    "equipamentos": ["Rolo", "Trincha", "Escada (contratante)"],
    "epi_necessario": ["Cinto de segurança", "Capacete", "Botina antiderrapante"],
    "tags": ["pintura", "externa", "fachada"],
    "obs": "Ritmo menor pela logística de escada e altura. Andaime é por conta do contratante.",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "P004",
    "categoria": "Pintura",
    "nome": "Textura / grafiato",
    "unidade": "m2",
    "producao_dia": 12,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Textura acrílica",
      "desempenadeira de espuma",
      "rolo especial"
    ],
    "tempo_por_unidade_h": 0.67,
    "nivel_dificuldade": "alto",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Desempenadeira de espuma", "Rolo de textura"],
    "epi_necessario": ["Máscara", "Óculos"],
    "tags": ["textura", "grafiato", "acabamento decorativo"],
    "obs": "Inclui aplicação e acabamento com rolo rústico ou lisotel. Exige nivelamento base.",
    "requer_visita_tecnica": false,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "P005",
    "categoria": "Pintura",
    "nome": "Epóxi em piso ou parede",
    "unidade": "m2",
    "producao_dia": 20,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Tinta epóxi",
      "primer",
      "rolo de espuma curta"
    ],
    "tempo_por_unidade_h": 0.4,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": false,
    "equipamentos": ["Rolo de espuma", "Bandeja", "Máscara química"],
    "epi_necessario": ["Máscara com filtro químico", "Luva nitrílica", "Óculos de proteção"],
    "tags": ["epóxi", "piso", "garagem", "área industrial"],
    "obs": "Piso deve estar limpo, seco e preparado. Cada demão precisa secar (cura 12h).",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "R001",
    "categoria": "Revestimento",
    "nome": "Assentamento de cerâmica (piso)",
    "unidade": "m2",
    "producao_dia": 8,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Argamassa AC-II",
      "espaçadores",
      "nível",
      "martelo de borracha"
    ],
    "tempo_por_unidade_h": 1,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Cortadeira de piso", "Desempenadeira dentada", "Nível"],
    "epi_necessario": ["Óculos de segurança", "Luva de raspa", "Protetor auricular"],
    "tags": ["cerâmica", "piso", "revestimento", "azulejo"],
    "obs": "Inclui cortes retos. Cortes curvos ou mosaico reduzem produção 40%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "R002",
    "categoria": "Revestimento",
    "nome": "Assentamento de porcelanato",
    "unidade": "m2",
    "producao_dia": 6,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Argamassa colante especial",
      "nível laser",
      "espaçador"
    ],
    "tempo_por_unidade_h": 1.3,
    "nivel_dificuldade": "alto",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Nível laser", "Cortadeira com água", "Sistema nivelador"],
    "epi_necessario": ["Óculos", "Luva", "Protetor auricular"],
    "tags": ["porcelanato", "revestimento", "acabamento premium"],
    "obs": "Mais pesado e exigente em nivelamento. Peças grandes (90x90) reduzem produção.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "R003",
    "categoria": "Revestimento",
    "nome": "Azulejo parede (banheiro / cozinha)",
    "unidade": "m2",
    "producao_dia": 7,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Argamassa AC-I",
      "espaçador fino",
      "nível",
      "desempenadeira"
    ],
    "tempo_por_unidade_h": 1.1,
    "nivel_dificuldade": "alto",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Cortadeira", "Nível a laser", "Desempenadeira dentada"],
    "epi_necessario": ["Óculos", "Luva"],
    "tags": ["azulejo", "parede", "banheiro", "cozinha"],
    "obs": "Juntas precisam de alinhamento milimétrico. Meias-peças aumentam o tempo.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "R004",
    "categoria": "Revestimento",
    "nome": "Rejunte de piso ou parede",
    "unidade": "m2",
    "producao_dia": 35,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Rejunte",
      "esponja",
      "balde",
      "rodo de borracha"
    ],
    "tempo_por_unidade_h": 0.23,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Espátula de borracha", "Esponja", "Balde"],
    "epi_necessario": ["Luva de borracha"],
    "tags": ["rejunte", "piso", "parede", "acabamento"],
    "obs": "Inclui aplicação e limpeza pós-rejunte. Juntas largas aumentam consumo de material.",
    "requer_visita_tecnica": false,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "R005",
    "categoria": "Revestimento",
    "nome": "Piso laminado / vinílico (clique)",
    "unidade": "m2",
    "producao_dia": 20,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Manta de EVA",
      "espátula",
      "martelo de madeira",
      "esquadro"
    ],
    "tempo_por_unidade_h": 0.4,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Martelo", "Espaçadores", "Esquadro", "Serrinha"],
    "epi_necessario": [],
    "tags": ["laminado", "vinílico", "piso flutuante"],
    "obs": "Piso deve estar nivelado. Inclui manta de isolamento. Soleira não inclusa.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "T001",
    "categoria": "Telhado",
    "nome": "Reposição de telha (colonial ou ondulada)",
    "unidade": "m2",
    "producao_dia": 15,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Telhas (contratante)",
      "cumeeira",
      "pregos galvanizados"
    ],
    "tempo_por_unidade_h": 0.53,
    "nivel_dificuldade": "alto",
    "nivel_risco": 5,
    "requer_equipamento": true,
    "equipamentos": ["Cinto de segurança", "Capacete", "Bota com solado antiderrapante"],
    "epi_necessario": ["Cinto de segurança tipo paraquedista", "Capacete", "Botina de segurança", "Luva de vaqueta"],
    "tags": ["telhado", "telha", "cobertura"],
    "obs": "EPI obrigatório (cinto, capacete, bota). Pitch alto reduz produção em 30%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "T002",
    "categoria": "Telhado",
    "nome": "Manta impermeabilizante (laje ou calha)",
    "unidade": "m2",
    "producao_dia": 12,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Manta asfáltica",
      "primer",
      "maçarico",
      "pincel"
    ],
    "tempo_por_unidade_h": 0.67,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Maçarico", "Rolete de lã", "Pincel largo"],
    "epi_necessario": ["Luva térmica", "Óculos de segurança", "Máscara para fumaça", "Botina"],
    "tags": ["impermeabilização", "manta", "laje", "telhado"],
    "obs": "Inclui limpeza da superfície, primer e 2 demãos de manta.",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "T003",
    "categoria": "Telhado",
    "nome": "Calha de alumínio (instalação)",
    "unidade": "metro",
    "producao_dia": 20,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Calha",
      "suporte",
      "parafusos galvanizados",
      "fita de butila"
    ],
    "tempo_por_unidade_h": 0.4,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 3,
    "requer_equipamento": false,
    "equipamentos": ["Nível", "Furadeira", "Serrinha de metal"],
    "epi_necessario": ["Óculos", "Luva", "Botina"],
    "tags": ["calha", "telhado", "drenagem"],
    "obs": "Inclui nivelamento e caimento correto (1cm para cada 1m). Descida de água extra.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "E001",
    "categoria": "Elétrica",
    "nome": "Instalação elétrica (ponto simples — tomada/interruptor)",
    "unidade": "ponto",
    "producao_dia": 6,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Fio",
      "tomada",
      "caixa de embutir (contratante)"
    ],
    "tempo_por_unidade_h": 1.3,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Alicate", "Chave de fenda", "Detector de tensão", "Furadeira"],
    "epi_necessario": ["Luva isolante", "Óculos de segurança", "Bota de segurança"],
    "tags": ["elétrica", "tomada", "interruptor", "ponto"],
    "obs": "Troca simples em parede seca. Embutimento em alvenaria reduz para 4 pontos/dia.",
    "requer_visita_tecnica": true,
    "unidade_minima": 3,
    "ativo": true
  },
  {
    "id": "E002",
    "categoria": "Elétrica",
    "nome": "Instalação elétrica completa (com eletroduto)",
    "unidade": "ponto",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Eletroduto",
      "fio",
      "caixa",
      "disjuntor (contratante)"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "alto",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Martelete", "Alicate amperímetro", "Detector de tensão"],
    "epi_necessario": ["Luva isolante", "Óculos", "Bota", "Protetor auricular"],
    "tags": ["elétrica", "eletroduto", "instalação nova"],
    "obs": "Nova instalação embutida com passagem de fiação. Requer corte de alvenaria.",
    "requer_visita_tecnica": true,
    "unidade_minima": 3,
    "ativo": true
  },
  {
    "id": "E003",
    "categoria": "Elétrica",
    "nome": "Troca de disjuntor / organização de quadro",
    "unidade": "unidade",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Disjuntor (contratante)",
      "fita isolante",
      "terminal"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "alto",
    "nivel_risco": 5,
    "requer_equipamento": true,
    "equipamentos": ["Alicate", "Chave de fenda isolada", "Detector de tensão"],
    "epi_necessario": ["Luva isolante", "Óculos", "Bota"],
    "tags": ["elétrica", "disjuntor", "quadro de luz"],
    "obs": "Quadro com até 12 disjuntores. Quadros maiores cobrar por hora técnica.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "E004",
    "categoria": "Elétrica",
    "nome": "Instalação de câmera CFTV",
    "unidade": "câmera",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Câmera",
      "cabo coaxial ou rede",
      "conectores"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Crimpadeira", "Alicate"],
    "epi_necessario": ["Luva", "Óculos"],
    "tags": ["câmera", "CFTV", "segurança", "câmera de segurança"],
    "obs": "Inclui fixação, passagem de cabo e configuração básica no DVR.",
    "requer_visita_tecnica": true,
    "unidade_minima": 2,
    "ativo": true
  },
  {
    "id": "E005",
    "categoria": "Elétrica",
    "nome": "Instalação de suporte de TV",
    "unidade": "unidade",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Suporte",
      "bucha",
      "parafuso (contratante)"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Nível", "Chave philips"],
    "epi_necessario": [],
    "tags": ["suporte", "TV", "parede", "instalação"],
    "obs": "Inclui nivelar, fixar e organizar cabos. TV acima de 65' acrescentar 20%.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H001",
    "categoria": "Hidráulica",
    "nome": "Troca de torneira / registro",
    "unidade": "unidade",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Veda-rosca",
      "chave grifo",
      "vedante de borracha"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Chave grifo", "Chave de fenda", "Alicate"],
    "epi_necessario": [],
    "tags": ["hidráulica", "torneira", "registro", "vazamento"],
    "obs": "Torneiras expostas. Embutidas em parede aumentam 50% o tempo.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H002",
    "categoria": "Hidráulica",
    "nome": "Instalação de chuveiro elétrico",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Chuveiro (contratante)",
      "veda-rosca",
      "fio 4mm"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": false,
    "equipamentos": ["Chave grifo", "Chave de fenda", "Alicate"],
    "epi_necessario": ["Luva isolante", "Óculos"],
    "tags": ["chuveiro", "hidráulica", "elétrica", "banheiro"],
    "obs": "Inclui ligação elétrica e hidráulica. Teste de vazamento obrigatório antes de encerrar.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H003",
    "categoria": "Hidráulica",
    "nome": "Desentupimento de ralo ou pia",
    "unidade": "ponto",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Sonda elétrica",
      "produto desentupidor"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Sonda elétrica ou manual", "Produto desentupidor"],
    "epi_necessario": ["Luva de borracha", "Óculos", "Máscara"],
    "tags": ["desentupimento", "hidráulica", "ralo", "pia"],
    "obs": "Entupimentos simples. Obstruções na coluna principal ou caixa de gordura: cobrar separado.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H004",
    "categoria": "Hidráulica",
    "nome": "Limpeza de caixa d'água",
    "unidade": "unidade",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Hipoclorito de sódio",
      "escova",
      "balde",
      "rodo"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": false,
    "equipamentos": ["Escova", "Balde", "Bomba d'água manual (opcional)"],
    "epi_necessario": ["Luva", "Bota", "Máscara", "Óculos"],
    "tags": ["caixa d'água", "limpeza", "higienização"],
    "obs": "Até 10.000L por este valor. Acima disso acrescentar R$50 por 1.000L adicional.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H005",
    "categoria": "Hidráulica",
    "nome": "Instalação de vaso sanitário / caixa acoplada",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Vaso",
      "caixa",
      "parafusos",
      "vedação (contratante)"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Chave grifo", "Chave de fenda", "Nível"],
    "epi_necessario": ["Luva"],
    "tags": ["vaso sanitário", "banheiro", "hidráulica"],
    "obs": "Inclui nivelar, vedar e testar descarga. Requer desligar o registro geral.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "H006",
    "categoria": "Hidráulica",
    "nome": "Reparo em cano (vazamento aparente)",
    "unidade": "ponto",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Luva",
      "joelho",
      "veda-rosca",
      "cola PVC (contratante)"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Chave grifo", "Tubo de arremate", "Serrote"],
    "epi_necessario": ["Luva", "Óculos"],
    "tags": ["vazamento", "hidráulica", "cano", "reparo"],
    "obs": "Cano aparente (PVC ou metal). Embutido em parede: cobrar acréscimo de 50%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "M001",
    "categoria": "Marcenaria",
    "nome": "Instalação de porta de madeira com alizar",
    "unidade": "unidade",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Dobradiças",
      "parafusos",
      "massa de madeira",
      "alizar"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "alto",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Plaina", "Formão", "Furadeira", "Nível"],
    "epi_necessario": ["Óculos", "Luva", "Protetor auricular"],
    "tags": ["porta", "marcenaria", "alizar", "instalação"],
    "obs": "Inclui nivelamento, folga correta e instalação do alizar. Porta já pronta.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "M002",
    "categoria": "Marcenaria",
    "nome": "Instalação de porta sanfonada",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Trilho",
      "parafusos",
      "bucha (incluso na porta)"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Nível", "Chave philips"],
    "epi_necessario": [],
    "tags": ["porta sanfonada", "marcenaria", "instalação"],
    "obs": "Mais rápida que porta comum. Inclui regulagem do trilho e teste de funcionamento.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "M003",
    "categoria": "Marcenaria",
    "nome": "Instalação de armário pré-fabricado (módulo)",
    "unidade": "módulo",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Bucha",
      "parafusos",
      "nível (contratante fornece armário)"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 1,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Nível", "Chave philips", "Esquadro"],
    "epi_necessario": [],
    "tags": ["armário", "marcenaria", "modulado", "instalação"],
    "obs": "Módulo = 1 corpo de armário. Painel traseiro e porta inclusos na contagem.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "M004",
    "categoria": "Marcenaria",
    "nome": "Troca de fechadura (porta pronta)",
    "unidade": "unidade",
    "producao_dia": 6,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Fechadura (contratante)",
      "parafusos",
      "formão"
    ],
    "tempo_por_unidade_h": 1.3,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Formão", "Martelo", "Chave philips"],
    "epi_necessario": [],
    "tags": ["fechadura", "porta", "segurança", "manutenção"],
    "obs": "Porta já com furo. Abertura de cava nova aumenta o tempo para 1.5x.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "M005",
    "categoria": "Marcenaria",
    "nome": "Deck de madeira (estrutura simples)",
    "unidade": "m2",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Caibro",
      "tábua de deck",
      "parafusos inox",
      "impermeabilizante"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "alto",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Serra circular", "Furadeira", "Nível", "Trena"],
    "epi_necessario": ["Óculos", "Protetor auricular", "Luva", "Máscara"],
    "tags": ["deck", "madeira", "área externa", "terraço"],
    "obs": "Base já nivelada. Inclui estrutura de caibro e tábuas. Acabamento por conta do profissional.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "M006",
    "categoria": "Marcenaria",
    "nome": "Instalação de prateleira / nicho",
    "unidade": "unidade",
    "producao_dia": 6,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Bucha",
      "parafuso",
      "suporte (contratante)"
    ],
    "tempo_por_unidade_h": 1.3,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Nível", "Régua"],
    "epi_necessario": [],
    "tags": ["prateleira", "nicho", "parede", "instalação"],
    "obs": "Parede de alvenaria com furadeira. Drywall requer bucha específica.",
    "requer_visita_tecnica": false,
    "unidade_minima": 2,
    "ativo": true
  },
  {
    "id": "S001",
    "categoria": "Serralheria",
    "nome": "Solda MIG/MAG (estruturas finas)",
    "unidade": "metro",
    "producao_dia": 8,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Arame de solda (profissional fornece)",
      "gás CO2"
    ],
    "tempo_por_unidade_h": 1,
    "nivel_dificuldade": "alto",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Máquina de solda MIG", "Máscara de solda", "Luva de raspa"],
    "epi_necessario": ["Máscara de solda", "Luva de raspa", "Avental de couro", "Óculos de segurança"],
    "tags": ["solda", "MIG", "MAG", "serralheria", "metal"],
    "obs": "Declara equipamento no perfil. Chapas grossas acima de 5mm cobrar 50% a mais.",
    "requer_visita_tecnica": true,
    "unidade_minima": 2,
    "ativo": true
  },
  {
    "id": "S002",
    "categoria": "Serralheria",
    "nome": "Grade de ferro (fabricação e instalação)",
    "unidade": "m2",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Vergalhão",
      "ferro chato",
      "eletrodo",
      "tinta anticorrosiva"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "alto",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Solda", "Esmerilhadeira", "Grampo", "Esquadro"],
    "epi_necessario": ["Máscara de solda", "Luva", "Óculos", "Protetor auricular"],
    "tags": ["grade", "ferro", "serralheria", "segurança"],
    "obs": "Inclui fabricação, pintura anticorrosiva básica e instalação. Galvanização: acrescentar 30%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "S003",
    "categoria": "Serralheria",
    "nome": "Instalação de portão (portão já pronto)",
    "unidade": "unidade",
    "producao_dia": 1,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Dobradiças",
      "trava",
      "parafusos",
      "concreto para poste"
    ],
    "tempo_por_unidade_h": 8,
    "nivel_dificuldade": "alto",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Solda", "Nível", "Esmerilhadeira", "Betoneira (aluguel contratante)"],
    "epi_necessario": ["Capacete", "Botina", "Luva", "Óculos"],
    "tags": ["portão", "serralheria", "instalação"],
    "obs": "Portão já fabricado. Inclui nivelamento de postes, solda de dobradiça e regulagem.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "S004",
    "categoria": "Serralheria",
    "nome": "Corte e montagem de estrutura metálica (galpão/cobertura)",
    "unidade": "m2",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Perfil metálico",
      "parafuso",
      "disco de corte"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "alto",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Esmerilhadeira", "Furadeira", "Chave catraca", "Andaime"],
    "epi_necessario": ["Capacete", "Cinto de segurança", "Botina", "Óculos", "Luva"],
    "tags": ["estrutura metálica", "galpão", "cobertura", "serralheria"],
    "obs": "Estrutura simples. Inclui montagem dos perfis, não inclui telhamento.",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "G001",
    "categoria": "Gesso",
    "nome": "Gesso liso (massa de gesso em parede)",
    "unidade": "m2",
    "producao_dia": 12,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Gesso em pó",
      "desempenadeira de aço inox"
    ],
    "tempo_por_unidade_h": 0.67,
    "nivel_dificuldade": "alto",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Desempenadeira", "Régua de alumínio", "Lixa d'água"],
    "epi_necessario": ["Máscara contra pó", "Óculos", "Luva"],
    "tags": ["gesso", "parede", "massa de gesso", "acabamento"],
    "obs": "Requer lixamento fino após cura. Resultado pronto para pintura.",
    "requer_visita_tecnica": false,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "G002",
    "categoria": "Gesso",
    "nome": "Forro de PVC (banheiro / área de serviço)",
    "unidade": "m2",
    "producao_dia": 12,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Régua de PVC",
      "perfil de alumínio",
      "parafusos"
    ],
    "tempo_por_unidade_h": 0.67,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Nível laser", "Serrinha de corte"],
    "epi_necessario": ["Óculos", "Luva"],
    "tags": ["forro PVC", "banheiro", "teto", "revestimento"],
    "obs": "Inclui estrutura de suporte em madeira ou alumínio e fechamento com régua.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "G003",
    "categoria": "Gesso",
    "nome": "Gesso acartonado / drywall (parede simples)",
    "unidade": "m2",
    "producao_dia": 8,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Placa de drywall",
      "perfil de aço",
      "parafusos",
      "massa de rejunte"
    ],
    "tempo_por_unidade_h": 1,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Estilete", "Chave de gesso", "Parafusadeira"],
    "epi_necessario": ["Máscara", "Óculos"],
    "tags": ["drywall", "gesso acartonado", "parede seca"],
    "obs": "Parede simples, sem curvas. Inclui tratamento de juntas com fita e massa.",
    "requer_visita_tecnica": false,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "G004",
    "categoria": "Gesso",
    "nome": "Forro de gesso acartonado (teto plano)",
    "unidade": "m2",
    "producao_dia": 7,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Placa de drywall",
      "perfil",
      "parafusos",
      "fita",
      "massa"
    ],
    "tempo_por_unidade_h": 1.1,
    "nivel_dificuldade": "alto",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Andaime", "Parafusadeira", "Nível laser"],
    "epi_necessario": ["Capacete", "Óculos", "Máscara"],
    "tags": ["forro", "gesso", "teto", "drywall"],
    "obs": "Mais trabalhoso que parede pelo esforço acima da cabeça. Andaime incluso no cálculo.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "PE001",
    "categoria": "Pedreiro",
    "nome": "Reboco / chapisco (preparo de parede)",
    "unidade": "m2",
    "producao_dia": 15,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Cimento",
      "areia",
      "aditivo",
      "desempenadeira"
    ],
    "tempo_por_unidade_h": 0.53,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Desempenadeira", "Colher de pedreiro", "Régua de alumínio"],
    "epi_necessario": ["Luva", "Óculos", "Máscara"],
    "tags": ["reboco", "chapisco", "pedreiro", "preparo"],
    "obs": "Inclui chapisco (traço 1:3) e reboco desempenado. Para pintura ou revestimento.",
    "requer_visita_tecnica": false,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "PE002",
    "categoria": "Pedreiro",
    "nome": "Calçada de concreto",
    "unidade": "m2",
    "producao_dia": 6,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Cimento",
      "areia",
      "brita",
      "sarrafo",
      "tela (contratante)"
    ],
    "tempo_por_unidade_h": 1.3,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Enxada", "Picareta", "Betoneira (aluguel contratante)"],
    "epi_necessario": ["Luva", "Óculos", "Bota", "Máscara"],
    "tags": ["calçada", "concreto", "pedreiro", "piso externo"],
    "obs": "Espessura 8cm. Inclui compactação do solo, forma de madeira e desempenamento.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "PE003",
    "categoria": "Pedreiro",
    "nome": "Alvenaria — elevação de muro ou parede",
    "unidade": "m2",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Tijolo",
      "argamassa",
      "armação (contratante)"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": false,
    "equipamentos": ["Colher de pedreiro", "Prumo", "Nível"],
    "epi_necessario": ["Capacete", "Bota", "Luva"],
    "tags": ["alvenaria", "muro", "parede", "pedreiro", "tijolo"],
    "obs": "Até 2m de altura. Acima disso requer andaime e cobrar adicional de 20%.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "PE004",
    "categoria": "Pedreiro",
    "nome": "Demolição de parede (alvenaria)",
    "unidade": "m2",
    "producao_dia": 10,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Marreta",
      "talhadeira",
      "equipamento de proteção"
    ],
    "tempo_por_unidade_h": 0.8,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Martelete", "Marreta", "Talhadeira", "EPI"],
    "epi_necessario": ["Capacete", "Óculos", "Protetor auricular", "Luva", "Bota", "Máscara contra pó"],
    "tags": ["demolição", "parede", "pedreiro"],
    "obs": "Inclui quebra e empilhamento do entulho. Caçamba por conta do contratante.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "I001",
    "categoria": "Impermeabilização",
    "nome": "Impermeabilização de banheiro (parede e piso)",
    "unidade": "m2",
    "producao_dia": 8,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Primer",
      "manta líquida",
      "fita de reforço"
    ],
    "tempo_por_unidade_h": 1,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Pincel largo", "Rolo de espuma"],
    "epi_necessario": ["Luva", "Máscara", "Óculos"],
    "tags": ["impermeabilização", "banheiro", "manta", "vedação"],
    "obs": "Inclui 2 demãos de manta e teste de estanqueidade (48h de água parada).",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "I002",
    "categoria": "Impermeabilização",
    "nome": "Impermeabilização de laje (cobertura)",
    "unidade": "m2",
    "producao_dia": 10,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Argamassa polimérica ou manta asfáltica",
      "primer"
    ],
    "tempo_por_unidade_h": 0.8,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": false,
    "equipamentos": ["Rolete de lã", "Pincel", "EPI"],
    "epi_necessario": ["Luva", "Máscara", "Óculos", "Botina"],
    "tags": ["impermeabilização", "laje", "cobertura", "infiltração"],
    "obs": "Inclui limpeza da laje, 2 demãos de produto e teste de cura mínimo 72h.",
    "requer_visita_tecnica": true,
    "unidade_minima": 10,
    "ativo": true
  },
  {
    "id": "L001",
    "categoria": "Limpeza",
    "nome": "Limpeza pós-obra",
    "unidade": "m2",
    "producao_dia": 50,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Removedor",
      "detergente",
      "esponja",
      "rodo",
      "mop"
    ],
    "tempo_por_unidade_h": 0.16,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 2,
    "requer_equipamento": false,
    "equipamentos": ["Rodo", "Mop", "Esponja", "Balde"],
    "epi_necessario": ["Luva", "Máscara", "Óculos"],
    "tags": ["limpeza", "pós-obra", "faxina"],
    "obs": "Inclui vidros, pisos, azulejos e retirada de rebarbas de massa. Caçamba: contratante.",
    "requer_visita_tecnica": true,
    "unidade_minima": 20,
    "ativo": true
  },
  {
    "id": "L002",
    "categoria": "Limpeza",
    "nome": "Limpeza residencial geral (por cômodo)",
    "unidade": "cômodo",
    "producao_dia": 5,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Produtos de limpeza",
      "pano",
      "vassoura",
      "mop"
    ],
    "tempo_por_unidade_h": 1.6,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Vassoura", "Rodo", "Mop", "Balde", "Pano"],
    "epi_necessario": ["Luva"],
    "tags": ["limpeza", "residencial", "faxina", "doméstico"],
    "obs": "Cômodo = quarto, sala, banheiro ou cozinha. Banheiro conta como 1 cômodo.",
    "requer_visita_tecnica": false,
    "unidade_minima": 2,
    "ativo": true
  },
  {
    "id": "L003",
    "categoria": "Limpeza",
    "nome": "Roçagem / jardinagem (terreno plano)",
    "unidade": "m2",
    "producao_dia": 800,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Roçadeira a gasolina ou elétrica",
      "protetor de orelha",
      "óculos"
    ],
    "tempo_por_unidade_h": 0.01,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Roçadeira", "EPI completo"],
    "epi_necessario": ["Protetor auricular", "Óculos", "Luva", "Bota", "Calça comprida"],
    "tags": ["jardinagem", "roçagem", "grama", "terreno"],
    "obs": "Terrenos planos com vegetação baixa. Mato alto reduz produção 50%. Valor mínimo: R$80.",
    "requer_visita_tecnica": true,
    "unidade_minima": 100,
    "ativo": true
  },
  {
    "id": "L004",
    "categoria": "Limpeza",
    "nome": "Limpeza de ar-condicionado (split)",
    "unidade": "unidade",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Produto antimofo",
      "pistola de pressão",
      "pano",
      "balde"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Pistola de ar", "Produto específico", "Proteção plástica"],
    "epi_necessario": ["Máscara", "Luva", "Óculos"],
    "tags": ["ar-condicionado", "split", "limpeza", "higienização"],
    "obs": "Limpeza do filtro, evaporador e bandeja de condensação. Sem recarga de gás.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "C001",
    "categoria": "Climatização",
    "nome": "Instalação de ar-condicionado split (até 12.000 BTU)",
    "unidade": "unidade",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Suporte",
      "cabo elétrico",
      "tubulação de cobre",
      "dreno"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "alto",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Bomba de vácuo", "Manifold", "Equipamento de carga"],
    "epi_necessario": ["Luva", "Óculos", "Cinto de segurança", "Capacete"],
    "tags": ["ar-condicionado", "split", "instalação", "climatização"],
    "obs": "Inclui passagem de tubulação até 3m. Distância maior cobrar por metro adicional.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "C002",
    "categoria": "Climatização",
    "nome": "Instalação de ventilador de teto",
    "unidade": "unidade",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Ventilador (contratante)",
      "fio",
      "caixa de embutir"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 3,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Alicate", "Chave de fenda"],
    "epi_necessario": ["Óculos", "Luva", "Capacete"],
    "tags": ["ventilador", "teto", "instalação", "elétrica"],
    "obs": "Inclui ligação elétrica e teste de balanceamento. Teto de drywall: acrescentar 20%.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "J001",
    "categoria": "Jardinagem",
    "nome": "Plantio e ajardinamento (canteiros)",
    "unidade": "m2",
    "producao_dia": 15,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Terra",
      "adubo",
      "plantas (contratante)",
      "pá",
      "rastelo"
    ],
    "tempo_por_unidade_h": 0.53,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Pá", "Enxadinha", "Rastelo"],
    "epi_necessario": ["Luva", "Óculos"],
    "tags": ["jardinagem", "plantio", "canteiro", "paisagismo"],
    "obs": "Inclui preparo do solo e plantio. Projeto de paisagismo cobrar separado.",
    "requer_visita_tecnica": true,
    "unidade_minima": 5,
    "ativo": true
  },
  {
    "id": "J002",
    "categoria": "Jardinagem",
    "nome": "Poda de árvore (pequeno porte)",
    "unidade": "unidade",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Tesoura de poda",
      "serrote",
      "luva",
      "óculos"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": false,
    "equipamentos": ["Tesoura de poda", "Serrote", "Escada"],
    "epi_necessario": ["Capacete", "Óculos", "Luva", "Cinto de segurança (se altura)"],
    "tags": ["poda", "árvore", "jardinagem"],
    "obs": "Árvore até 4m. Acima disso requer equipamento especial e cobrar por porte.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "D001",
    "categoria": "Dedetização",
    "nome": "Dedetização residencial (até 100m²)",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Inseticida concentrado",
      "bomba costal",
      "EPI completo"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "médio",
    "nivel_risco": 4,
    "requer_equipamento": true,
    "equipamentos": ["Bomba costal", "EPI", "Produto homologado"],
    "epi_necessario": ["Máscara com filtro químico", "Luva nitrílica", "Óculos", "Macacão impermeável", "Botina"],
    "tags": ["dedetização", "pragas", "insetos", "rato"],
    "obs": "Inclui baratas, formigas e aranhas. Pragas específicas (cupim, besouro) cobrar separado.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "MU001",
    "categoria": "Mudança",
    "nome": "Desmontagem e montagem de móvel (cama ou guarda-roupa)",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "profissional",
    "materiais": [
      "Chave philips",
      "chave Allen",
      "martelo de borracha"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Chave philips", "Allen", "Martelo"],
    "epi_necessario": ["Luva"],
    "tags": ["mudança", "móvel", "montagem", "desmontagem"],
    "obs": "Guarda-roupa de 6 portas conta como 2 unidades. Inclui reaperto de ferragens.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "ST001",
    "categoria": "Smart Home & Tecnologia",
    "nome": "Configuração de assistentes virtuais (Alexa/Google Home)",
    "unidade": "sessão",
    "producao_dia": 4,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Dispositivo assistente (contratante)",
      "aplicativo",
      "conta Wi-Fi"
    ],
    "tempo_por_unidade_h": 2,
    "nivel_dificuldade": "baixo",
    "nivel_risco": 1,
    "requer_equipamento": false,
    "equipamentos": ["Smartphone", "Acesso à internet"],
    "epi_necessario": [],
    "tags": ["assistente virtual", "Alexa", "Google Home", "smart home", "automação"],
    "obs": "Inclui conexão de até 3 dispositivos inteligentes (lâmpadas, tomadas). Mais de 3 cobrar por hora adicional.",
    "requer_visita_tecnica": false,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "ST002",
    "categoria": "Smart Home & Tecnologia",
    "nome": "Instalação de fechadura inteligente ou interruptor Wi-Fi",
    "unidade": "unidade",
    "producao_dia": 3,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Fechadura inteligente / interruptor (contratante)",
      "parafusos",
      "fios (se necessário)"
    ],
    "tempo_por_unidade_h": 2.7,
    "nivel_dificuldade": "médio",
    "nivel_risco": 2,
    "requer_equipamento": true,
    "equipamentos": ["Furadeira", "Chave de fenda", "Detector de tensão (se elétrico)"],
    "epi_necessario": ["Luva", "Óculos"],
    "tags": ["fechadura inteligente", "interruptor Wi-Fi", "automação", "smart home"],
    "obs": "Inclui configuração no aplicativo e pareamento com rede. Não inclui instalação elétrica complexa.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  },
  {
    "id": "ST003",
    "categoria": "Smart Home & Tecnologia",
    "nome": "Otimização de rede Mesh / Wi-Fi doméstico",
    "unidade": "sessão",
    "producao_dia": 2,
    "diaria_base": 300,
    "material_por_conta": "contratante",
    "materiais": [
      "Roteadores Mesh (contratante)",
      "cabo de rede (se necessário)"
    ],
    "tempo_por_unidade_h": 4,
    "nivel_dificuldade": "alto",
    "nivel_risco": 1,
    "requer_equipamento": true,
    "equipamentos": ["Notebook", "Aplicativo de análise de rede", "Crimpador de cabos (opcional)"],
    "epi_necessario": [],
    "tags": ["Wi-Fi", "Mesh", "rede", "internet", "otimização"],
    "obs": "Inclui análise de cobertura, posicionamento dos nós, configuração de rede e testes de velocidade. Até 3 nós.",
    "requer_visita_tecnica": true,
    "unidade_minima": 1,
    "ativo": true
  }
]